core/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pasundayag.urls", namespace="pasundayag")),
    path("account/", include("account.urls", namespace="account")),
    path("__debug__/", include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pasundayag/urls.py
from django.urls import path

from . import views

app_name = "pasundayag"

urlpatterns = [
    path("", views.index, name="dashboard"),
    path("dashboard/<int:year>", views.index_02, name="dashboard"),
    path("dashboard-rating/<int:year>-<str:rating>", views.index_03, name="dashboard-rating"),
    path("ipcr-list", views.ipcr_all, name="ipcr-list"),
    path("personnel-ipcr-list/<personnel_id>", views.ipcr_per_personnel, name="personnel-ipcr-list"),
    path("academic-title-list", views.academic_title, name="academic-title-list"),
    path("personnel-list/<slug:slug>", views.personnel_per_title, name="personnel-list"),
    path("rate-personnel/<personnel_id>-<int:year>-<str:period>/", views.rate_personnel, name="rate-personnel"),
    path(
        "update-personnel-ipcr/<int:pk>-<str:personnel_name>-<int:year>-<str:period>/",
        views.update_personnel_ipcr,
        name="update-personnel-ipcr",
    ),
    path(
        "ipcr-detail-rating/<personnel_id>-<int:year>-<str:period>/",
        views.ipcr_detail_rating,
        name="ipcr-detail-rating",
    ),
    path("ipcr-detail-analytics/<personnel_id>/", views.ipcr_detail_analytics, name="ipcr-detail-analytics"),
    path("rank-list/<slug:slug>/", views.ipcr_per_rank, name="rank-list"),
    path("logout", views.logoutuser, name="logout"),
    path("annualipcr-chart/", views.annualipcr_chart, name="annualipcr-chart"),
]

pasundayag/forms.py
import datetime
import os

from django import forms
from django.db.models import Q
from django.forms import modelformset_factory

from .models import (
    IPCR,
    Function,
    Personnel,
    PersonnelFunctionIPCR,
    PersonnelSubfunctionIPCR,
    Subfunction,
)

FunctionFormSet = modelformset_factory(
    PersonnelFunctionIPCR, fields=("accomplishments", "rating_Q", "rating_E", "rating_T", "remarks")
)

SubfunctionFormSet = modelformset_factory(
    PersonnelSubfunctionIPCR, fields=("accomplishments", "rating_Q", "rating_E", "rating_T", "remarks")
)


class YearSelect(forms.Select):
    def __init__(self, attrs=None):
        year_range = range(1990, datetime.date.today().year + 1)
        choices = [("", "Please select year...")] + [(year, year) for year in year_range]
        super().__init__(attrs, choices)


class PersonnelIPCRForm(forms.ModelForm):
    year = forms.IntegerField(widget=YearSelect, initial="")

    class Meta:
        model = PersonnelFunctionIPCR
        fields = (
            "personnel",
            "year",
            "period",
            "function",
            "subfunction",
            "accomplishments",
            "rating_Q",
            "rating_E",
            "rating_T",
            "remarks",
        )

    subfunction = forms.ModelChoiceField(queryset=Subfunction.objects.all())

    def __init__(self, *args, **kwargs):
        super(PersonnelIPCRForm, self).__init__(*args, **kwargs)
        self.fields["personnel"].choices = [(None, "Please select personnel to rate...")] + list(
            self.fields["personnel"].choices
        )[1:]
        self.fields["year"].widget.attrs["class"] = "form-control"
        self.fields["period"].widget.attrs["class"] = "form-control"
        self.fields["accomplishments"].widget.attrs["class"] = "form-control"
        self.fields["remarks"].widget.attrs["class"] = "form-control"


class PersonnelFunctionIPCRForm(forms.ModelForm):
    year = forms.IntegerField(widget=YearSelect, initial="")
    personnel = forms.ModelChoiceField(
        queryset=Personnel.objects.filter(~Q(is_superuser=True) & ~Q(is_staff=True)),
        initial=None,
        empty_label="Please select a personnel to rate...",
        widget=forms.Select(attrs={"class": "form-control"}),
    )
    function = forms.ModelChoiceField(
        queryset=Function.objects.all(),
        initial=None,
        empty_label="Please select a function...",
        widget=forms.Select(attrs={"class": "form-control"}),
    )

    rating_Q = forms.IntegerFieldwidget = forms.Select(attrs={"class": "form-control"})
    rating_E = forms.IntegerFieldwidget = forms.Select(attrs={"class": "form-control"})
    rating_T = forms.IntegerFieldwidget = forms.Select(attrs={"class": "form-control"})

    class Meta:
        model = PersonnelFunctionIPCR
        fields = ("personnel", "year", "period", "accomplishments", "rating_Q", "rating_E", "rating_T", "remarks")

    def __init__(self, *args, **kwargs):
        super(PersonnelFunctionIPCRForm, self).__init__(*args, **kwargs)
        self.fields["personnel"].choices = [(None, "Please select personnel to rate...")] + list(
            self.fields["personnel"].choices
        )[1:]
        self.fields["year"].widget.attrs["class"] = "form-control"
        self.fields["period"].widget.attrs["class"] = "form-control"
        self.fields["accomplishments"].widget.attrs["class"] = "form-control"
        self.fields["remarks"].widget.attrs["class"] = "form-control"


class PersonnelSubfunctionIPCRForm(forms.ModelForm):
    year = forms.IntegerField(widget=YearSelect, initial="")
    personnel = forms.ModelChoiceField(
        queryset=Personnel.objects.filter(~Q(is_superuser=True) & ~Q(is_staff=True)),
        initial=None,
        empty_label="Please select a personnel to rate...",
        widget=forms.Select(attrs={"class": "form-control"}),
    )
    subfunction = forms.ModelChoiceField(
        queryset=Subfunction.objects.all(),
        initial=None,
        empty_label="Please select a function...",
        widget=forms.Select(attrs={"class": "form-control"}),
    )

    class Meta:
        model = PersonnelSubfunctionIPCR
        fields = ("personnel", "year", "period", "accomplishments", "rating_Q", "rating_E", "rating_T", "remarks")

    def __init__(self, *args, **kwargs):
        super(PersonnelSubfunctionIPCRForm, self).__init__(*args, **kwargs)
        self.fields["personnel"].choices = [(None, "Please select personnel to rate...")] + list(
            self.fields["personnel"].choices
        )[1:]
        self.fields["year"].widget.attrs["class"] = "form-control"
        self.fields["period"].widget.attrs["class"] = "form-control"
        self.fields["accomplishments"].widget.attrs["class"] = "form-control"
        self.fields["remarks"].widget.attrs["class"] = "form-control"


class IPCRForm(forms.ModelForm):
    class Meta:
        model = IPCR
        fields = "__all__"

pasundayag/views.py
from datetime import date

import numpy as np
import pandas as pd
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render

from django.contrib.auth.decorators import user_passes_test

from .forms import (
    FunctionFormSet,
    IPCRForm,
    PersonnelFunctionIPCRForm,
    PersonnelIPCRForm,
    PersonnelSubfunctionIPCRForm,
    SubfunctionFormSet,
)
from .models import (
    IPCR,
    AnnualIPCR,
    Area,
    Function,
    Personnel,
    PersonnelFunctionIPCR,
    PersonnelSubfunctionIPCR,
    Rank,
    Subfunction,
)

area_list = Area.objects.all()
context = {"area_list": area_list, "area_list_limited": area_list[:3]}


@login_required
@user_passes_test(lambda u: u.is_superuser)
def index(request):
    ipcr_list = IPCR.objects.prefetch_related("ipcr_image").filter(is_active=True)
    current_month = date.today().month
    current_year = date.today().year
    years = range(current_year, current_year - 10, -1)

    annual_counts = []
    ipcrs = AnnualIPCR.objects.filter(year=current_year)
    for annualipcr in ipcrs:
        annualipcr.calculate_annual_numerical_rating()
    os = ipcrs.filter(annual_adjectival_rating="Outstanding").count()
    vsf = ipcrs.filter(annual_adjectival_rating="Very Satisfactory").count()
    sf = ipcrs.filter(annual_adjectival_rating="Satisfactory").count()
    usf = ipcrs.filter(annual_adjectival_rating="Unsatisfactory").count()
    pr = ipcrs.filter(annual_adjectival_rating="Poor").count()
    annual_counts.append(
        {
            "year": current_year,
            "os": os,
            "vsf": vsf,
            "sf": sf,
            "usf": usf,
            "pr": pr,
        }
    )

    context = {
        "ipcrs": ipcr_list,
        "annual_counts": annual_counts,
        "years": years,
        "current_year": current_year,
        "os_label": "Outstanding",
        "vsf_label": "Very Satisfactory",
        "sf_label": "Satisfactory",
        "usf_label": "Unsatisfactory",
        "pr_label": "Poor",
    }
    return render(request, "pasundayag/index.html", context)

@user_passes_test(lambda u: u.is_superuser)
def index_02(request, year):
    ipcr_list = IPCR.objects.prefetch_related("ipcr_image").filter(is_active=True)
    current_month = date.today().month
    current_year = date.today().year
    years = range(current_year, current_year - 10, -1)

    annual_counts = []
    ipcrs = AnnualIPCR.objects.filter(year=year)
    for annualipcr in ipcrs:
        annualipcr.calculate_annual_numerical_rating()
    os = ipcrs.filter(annual_adjectival_rating="Outstanding").count()
    vsf = ipcrs.filter(annual_adjectival_rating="Very Satisfactory").count()
    sf = ipcrs.filter(annual_adjectival_rating="Satisfactory").count()
    usf = ipcrs.filter(annual_adjectival_rating="Unsatisfactory").count()
    pr = ipcrs.filter(annual_adjectival_rating="Poor").count()
    annual_counts.append(
        {
            "year": current_year,
            "os": os,
            "vsf": vsf,
            "sf": sf,
            "usf": usf,
            "pr": pr,
        }
    )

    context = {
        "ipcrs": ipcr_list,
        "annual_counts": annual_counts,
        "years": years,
        "current_year": current_year,
        "os_label": "Outstanding",
        "vsf_label": "Very Satisfactory",
        "sf_label": "Satisfactory",
        "usf_label": "Unsatisfactory",
        "pr_label": "Poor",
    }
    context["year"] = year
    context["current_year"] = year
    return render(request, "pasundayag/index_02.html", context)

@user_passes_test(lambda u: u.is_superuser)
def index_03(request, year, rating):
    annual_ipcr_list = AnnualIPCR.objects.filter(annual_adjectival_rating=rating, year=year).order_by(
        "-annual_numerical_rating"
    )
    annual_ipcr_count = AnnualIPCR.objects.filter(annual_adjectival_rating=rating, year=year).count()
    current_year = date.today().year
    years = range(current_year, current_year - 10, -1)
    context["rating"] = rating
    context["annual_ipcr_list"] = annual_ipcr_list
    context["annual_ipcr_count"] = annual_ipcr_count
    context["years"] = years

    return render(request, "pasundayag/index_03.html", context)

@user_passes_test(lambda u: u.is_superuser)
def ipcr_all(request):
    personnel_list = Personnel.objects.filter(
        ~Q(is_superuser=True),
        ~Q(is_staff=True),
        id__in=IPCR.objects.values_list('personnel_id', flat=True).distinct()
    )
    all_personnel = Personnel.objects.filter(~Q(is_superuser=True) & ~Q(is_staff=True))
    personnel_count = personnel_list.count()
    ipcrs = IPCR.objects.prefetch_related("ipcr_image").filter(is_active=True)
    paginator = Paginator(personnel_list, 10)
    page = request.GET.get("page")
    try:
        personnel_list = paginator.page(page)
    except PageNotAnInteger:
        personnel_list = paginator.page(1)
    except EmptyPage:
        personnel_list = paginator.page(paginator.num_pages)
    current_year = date.today().year
    years = range(current_year, current_year - 10, -1)
    context = {
        "personnel_list": personnel_list,
        "all_personnel": all_personnel,
        "personnel_count": personnel_count,
        "ipcrs": ipcrs,
        "years": years,
    }
    return render(request, "pasundayag/ipcr_all.html", context)

@login_required
def ipcr_per_personnel(request, personnel_id):
    personnel = Personnel.objects.get(pk=personnel_id)
    ipcrs = IPCR.objects.filter(Q(personnel_id=personnel_id)).order_by("-year")
    paginator = Paginator(ipcrs, 10)
    page = request.GET.get("page")
    try:
        ipcrs = paginator.page(page)
    except PageNotAnInteger:
        ipcrs = paginator.page(1)
    except EmptyPage:
        ipcrs = paginator.page(paginator.num_pages)
    pf_ipcr_list = PersonnelFunctionIPCR.objects.all()
    psf_ipcr = PersonnelSubfunctionIPCR.objects.all()
    current_year = date.today().year
    years = range(current_year, current_year - 10, -1)
    context["ipcrs"] = ipcrs
    context["personnel"] = personnel
    context["ipcrs"] = ipcrs
    context["pf_ipcr_list"] = pf_ipcr_list
    context["psf_ipcr"] = psf_ipcr
    context["years"] = years
    return render(request, "pasundayag/ipcr_per_personnel.html", context)

@user_passes_test(lambda u: u.is_superuser)
def ipcr_per_rank(request, slug=None):
    rank = get_object_or_404(Rank, slug=slug)
    ipcr_list = IPCR.objects.filter(personnel__rank=rank)
    personnel_list = Personnel.objects.filter(
        ~Q(is_superuser=True),
        ~Q(is_staff=True),
        id__in=IPCR.objects.values_list('personnel_id', flat=True).distinct(),
        rank=rank
    )
    all_personnel = Personnel.objects.filter(~Q(is_superuser=True) & ~Q(is_staff=True) & Q(rank=rank))
    personnel_count = personnel_list.count()
    paginator = Paginator(personnel_list, 10)
    page = request.GET.get("page")
    try:
        personnel_list = paginator.page(page)
    except PageNotAnInteger:
        personnel_list = paginator.page(1)
    except EmptyPage:
        personnel_list = paginator.page(paginator.num_pages)
    current_year = date.today().year
    years = range(current_year, current_year - 10, -1)
    context = {
        "personnel_list": personnel_list,
        "all_personnel": all_personnel,
        "personnel_count": personnel_count,
        "rank": rank,
        "ipcr_list": ipcr_list,
        "years": years,
    }

    return render(request, "pasundayag/ipcr_per_rank.html", context)

@user_passes_test(lambda u: u.is_superuser)
def ipcr_add(request):
    area_list = Area.objects.all()
    function_list = Function.objects.all()
    sfunction_list = Subfunction.objects.all()
    form1 = PersonnelFunctionIPCRForm
    form2 = PersonnelSubfunctionIPCRForm

    context["area_list"] = area_list
    context["function_list"] = function_list
    context["sfunction_list"] = sfunction_list
    context["form1"] = form1
    context["form2"] = form2
    return render(request, "pasundayag/ipcr_add.html", context)

@login_required
def ipcr_detail_rating(request, personnel_id, year, period):
    current_year = date.today().year
    personnel = Personnel.objects.get(pk=personnel_id)
    years = range(current_year, current_year - 10, -1)
    try:
        ipcr = IPCR.objects.get(personnel_id=personnel_id, year=year, period=period)

    except IPCR.DoesNotExist:
        ipcr = None

    if ipcr:
        if period == "Jan-Jun":
            prev_period = "Jul-Dec"
            prev_year = str(int(year) - 1)
        else:
            prev_period = "Jan-Jun"
            prev_year = year

        try:
            prev_ipcr = (
                IPCR.objects.filter(personnel_id=personnel_id, year=prev_year, period=prev_period)
                .order_by("-period")
                .first()
            )
        except IPCR.DoesNotExist:
            prev_ipcr = None

        ipcr.calculate_stra_total()
        ipcr.calculate_core_acad_total()
        ipcr.calculate_core_prod_total()
        ipcr.calculate_core_tech_total()
        ipcr.calculate_supp_total()
        ipcr.calculate_final_numerical_rating()
        ipcr.stra_save()
        ipcr.core_acad_save()
        ipcr.core_prod_save()
        ipcr.core_tech_save()
        ipcr.supp_save()

        if prev_ipcr:
            prev_ipcr.calculate_stra_total()
            prev_ipcr.calculate_core_acad_total()
            prev_ipcr.calculate_core_prod_total()
            prev_ipcr.calculate_core_tech_total()
            prev_ipcr.calculate_supp_total()
            prev_ipcr.calculate_final_numerical_rating()
            prev_ipcr.stra_save()
            prev_ipcr.core_acad_save()
            prev_ipcr.core_prod_save()
            prev_ipcr.core_tech_save()
            prev_ipcr.supp_save()

templates/pasundayag/academic_title.html
{% extends "adminlte/base.html" %}
{% load static %}

{% block extra_head %}
  <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />
  <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js"></script>
  <style>
    .dropdown-toggle .fa-caret-down {
      transition: all 0.3s;
      transform: rotate(0deg);
    }
    
    .dropdown.show .fa-caret-down {
      transform: rotate(180deg);
    }
  </style>
{% endblock extra_head %}

{% block content %}

  <div class="container-fluid">
    <div class="alert alert-primary fw600 rounded-0 border-0 pb-3" role="alert">
      <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-info-circle me-2"
        viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
        <path d="M8.93 6.588l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
      </svg>
      CSU Perfomance Appraisal System - <u>Click here for our latest updates</u>. We are doing our best to make CSU the spearhead of the future. Thank you for
      your patience and support.
    </div>
  </div>

  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">CSU Perfomance Appraisal System</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">IPCRs</li>
          </ol>
        </div>
      </div>
    </div>
  </div>
  <section class="content">
    <div class="container-fluid"> 
      <table id="rankTable" class="table table-hover shadow">
        <thead>
          <tr>
            <th scope="col">Academic Title</th>
            <th scope="col">Personnel Count</th>
          </tr>
        </thead>
        <tbody>
          {% for rank in rank_list %}
          <tr>
            <td><a href="{% url 'pasundayag:personnel-list' rank.slug %}">{{rank.name}}</a></td>
            <td>{{rank.personnel_count}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </section>
  
  {% endblock %}

  {% block extra_js %}
  <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
  <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>

  <script>
    $(document).ready(function() {
      $('#rankTable').dataTable( {
          "columns": [
              { "data": "pk", "type": "num" },
              { "data": "personnel_count", "type": "num" }
          ],
          "select": {
              "style": "os",
              "items": "cell"
          },
          "paging": true
      } );
  } );
  </script>
  {% endblock %}

templates/pasundayag/ipcr_all.html
{% extends "adminlte/base.html" %}
{% load static %}

{% block extra_head %}
  <style>
    .dropdown-toggle .fa-caret-down {
      transition: all 0.3s;
      transform: rotate(0deg);
    }
    
    .dropdown.show .fa-caret-down {
      transform: rotate(180deg);
    }
  </style>
{% endblock extra_head %}

{% block content %}

  <div class="container-fluid">
    <div class="alert alert-primary fw600 rounded-0 border-0 pb-3" role="alert">
      <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-info-circle me-2"
        viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
        <path d="M8.93 6.588l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
      </svg>
      CSU Perfomance Appraisal System - <u>Click here for our latest updates</u>. We are doing our best to make CSU the spearhead of the future. Thank you for
      your patience and support.
    </div>
  </div>

  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">CSU Perfomance Appraisal System</h1>
        </div>
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">IPCR - All</li>
          </ol>
        </div>
      </div>


      <div class="row mb-2">
        <div class="col-sm-8">
          <div class="pb-2">
            <form id="eval-form">
              <div class="form-row">
                <div class="col">
                  <select class="form-control" id="personnel" name="personnel" required>
                    <option value="" selected>Select personnel to rate...</option>
                    {% for personnel in all_personnel %}
                      <option value="{{ personnel.id }}">{{ personnel.name }}</option>
                    {% endfor %}
                  </select>
                </div>
                <div class="col">
                  <select class="form-control" id="year" name="year" required>
                    <option value="" selected>Select year...</option>
                    {% for year in years %}
                      <option value="{{ year }}">{{ year }}</option>
                    {% endfor %}
                  </select>
                </div>
                <div class="col">
                  <select class="form-control" id="period" name="period" required>
                    <option value="" selected>Select period...</option>
                      <option value="Jan-Jun">January to June</option>
                      <option value="Jul-Dec">July to December</option>
                  </select>
                </div>
                <div class="col">
                  <button class="btn btn-primary" type="button" onclick="redirectToEval(document.getElementById('personnel').value, document.getElementById('year').value, document.getElementById('period').value)">Rate</button>
                  <button class="btn btn-primary" type="button" onclick="redirectToView(document.getElementById('personnel').value, document.getElementById('year').value, document.getElementById('period').value)">View</button>
                  <input type="hidden" id="personnel_id" name="personnel_id" value="">
                </div>
              </div>
            </form>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="pb-2">

            <form id="filter-form">
              <div class="form-row">
                <div class="col">
                  <select class="form-control" id="rank" name="rank" required>
                    <option value="" selected>All</option>
                    {% for r in ranks %}
                      <option value="{{ r.slug }}">{{ r.name }}</option>
                    {% endfor %}
                    </select>
                </div>
                <div class="col">
                  <button class="btn btn-primary" type="button" onclick="redirectToFilterView()">Filter</button>
                  <input type="hidden" id="rank_slug" name="rank_slug" value="">
                </div>
              </div>
            </form>

          </div>
        </div>
      </div>

    </div>
  </div>

  <section class="content">
    <div class="container"> 
		{% if not ipcrs %} 
		<div class="col-12">There are currently no active IPCRs.
		</div> 
		{% else %}
		<div class="row g-2">
			{% for personnel in personnel_list %}
			<div class="col mb-3">
        <div class="card mb-3 p-2 h-100">
          <div class="row g-0">
            <div class="col-md-12 p-3 text-center">
              {% if personnel.avatar %} 
              <img class="rounded-circle border" alt="Rounded Image" width="150" height="150" src="{{ personnel.avatar.url }}" alt="{{ image.image.alt_text }}"> 
              {% else %}
              <img class="rounded-circle border" alt="Rounded Image" width="150" height="150" src="{% static 'account/default-profile.jpg' %}" alt="{{ image.image.alt_text }}"> 
              {% endif %}
              <div class="card-body">
                <a class="h6 text-success text-decoration-none" href="{%url 'pasundayag:personnel-ipcr-list' personnel.id %}">{{ personnel.name|slice:":50" }}
                </a>
                <p class="card-text">
                  <small class="text-muted">{{personnel.rank}}</small>
                </p>
              </div>
            </div>
          </div>
        </div>
    	</div>
      {% endfor %}
    </div>

      {% endif %}
      {% if personnel_list.has_other_pages %}
          <nav aria-label="Page navigation container wow fadeInUp"></nav>
          <ul class="pagination justify-content-center wow fadeInUp py-3">
              {% if personnel_list.has_previous %}
              <li><a href="?page={{ personnel_list.previous_page_number }}"
                      class="btn btn-primary">&laquo; Prev </a></li>
              {% endif %}
              {% if personnel_list.has_next %}
              <li><a href="?page={{ personnel_list.next_page_number }}" class="btn btn-primary">
                      Next &raquo;</a></li>
              {% endif %}
          </ul>
          </nav>
        </div>
      {% endif %}      
            
        </div>
      </div>
    </div>
  </section>
  <script>
    
    function redirectToFilterView(rankSlug) {
      var rankSlug = document.getElementById('rank').value;
      document.getElementById('rank_slug').value = rankSlug;
      var form = document.getElementById('filter-form');
      form.action = "rank-list/" + rankSlug;
      form.submit();
    }

    function redirectToEval() {
      var personnelId = document.getElementById('personnel').value;
      var year = document.getElementById('year').value;
      var period = document.getElementById('period').value;
      document.getElementById('personnel_id').value = personnelId;
      var form = document.getElementById('eval-form');
      form.action = "rate-personnel/" + personnelId + "-" + year + "-" + period;
      form.submit();
    }
    
    function redirectToView() {
      var personnelId = document.getElementById('personnel').value;
      var year = document.getElementById('year').value;
      var period = document.getElementById('period').value;
      document.getElementById('personnel_id').value = personnelId;
      var form = document.getElementById('eval-form');
      form.action = "ipcr-detail-rating/" + personnelId + "-" + year + "-" + period;
      form.submit();
    }    
    </script>
  {% endblock %}