account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = "account"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="account/login.html", form_class=UserLoginForm),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(next_page="/account/login/"), name="logout"),
    path("register/", views.account_register, name="register"),
    path("activate/<slug:uidb64>/<slug:token>)/", views.account_activate, name="activate"),
    # Reset password
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/password_reset/password_reset_form.html",
            success_url="password_reset_email_confirm",
            email_template_name="account/password_reset/password_reset_email.html",
            form_class=PwdResetForm,
        ),
        name="pwdreset",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/password_reset/password_reset_confirm.html",
            success_url="password_reset_complete/",
            form_class=PwdResetConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/password_reset_email_confirm/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/Mg/password_reset_complete/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
        name="password_reset_complete",
    ),
    # User dashboard
    path("dashboard/", views.dashboard, name="dashboard"),
    path("profile/edit/", views.edit_details, name="edit_details"),
    path("profile/delete_user/", views.delete_user, name="delete_user"),
    path(
        "profile/delete_confirm/",
        TemplateView.as_view(template_name="account/dashboard/delete_confirm.html"),
        name="delete_confirmation",
    ),
    path("addresses/", views.view_address, name="addresses"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),
    path("user_orders/", views.user_orders, name="user_orders"),
    # Wish List
    path("wishlist", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"),
]

core/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pasundayag.urls", namespace="pasundayag")),
    path("account/", include("account.urls", namespace="account")),
    path("__debug__/", include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pasundayag/urls.py
from django.urls import path

from . import views

app_name = "pasundayag"

urlpatterns = [
    path("", views.index, name="dashboard"),
    path("dashboard/<int:year>", views.index_02, name="dashboard"),
    path("dashboard-rating/<int:year>-<str:rating>", views.index_03, name="dashboard-rating"),
    path("ipcr-list", views.ipcr_all, name="ipcr-list"),
    path("personnel-ipcr-list/<personnel_id>", views.ipcr_per_personnel, name="personnel-ipcr-list"),
    path("academic-title-list", views.academic_title, name="academic-title-list"),
    path("personnel-list/<slug:slug>", views.personnel_per_title, name="personnel-list"),
    path("rate-personnel/<personnel_id>-<int:year>-<str:period>/", views.rate_personnel, name="rate-personnel"),
    path(
        "update-personnel-ipcr/<int:pk>-<str:personnel_name>-<int:year>-<str:period>/",
        views.update_personnel_ipcr,
        name="update-personnel-ipcr",
    ),
    path(
        "ipcr-detail-rating/<personnel_id>-<int:year>-<str:period>/",
        views.ipcr_detail_rating,
        name="ipcr-detail-rating",
    ),
    path("ipcr-detail-analytics/<personnel_id>/", views.ipcr_detail_analytics, name="ipcr-detail-analytics"),
    path("rank-list/<slug:slug>/", views.ipcr_per_rank, name="rank-list"),
    path("logout", views.logoutuser, name="logout"),
    path("annualipcr-chart/", views.annualipcr_chart, name="annualipcr-chart"),
]

templates/adminlte/lib/_main_footer.html
<footer class="main-footer">
        <div class="float-right d-none d-sm-block">
        {% block footer_right %}
            <b>Version</b> {% block version %}0.1{% endblock %}
        {% endblock %}
    </div>

    {% block footer_left %}
    {% block legal %}
    <strong>Copyright &copy; {% now "Y" %}{% if not site %}.{% endif %} CSU Performance Appraisal System
    </strong> All rights
    reserved.
    {% endblock %}
    {% endblock %}
</footer>

templates/adminlte/lib/_main_header.html
{% load adminlte_helpers i18n %}
{% load static %}
<nav class="main-header navbar navbar-expand navbar-white navbar-light">


    <!-- Header Navbar: style can be found in header.less -->
    {% block nav_bar %}
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/" class="nav-link">Home</a>
        </li>
        {% if request.user.is_superuser %}
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/" class="nav-link">Admin</a>
        </li>
        {% endif %}
    </ul>

    {% block nav_bar_center %}
    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>
    {% endblock %}

    {% block nav_custom_menu %}
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <ul class="nav navbar-nav">
            {% block header_dropdowns %}
            {% block user_info %}
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="far fa-user fa-2x"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <a href="#" class="dropdown-item">
                            <!-- Message Start -->
                            <div class="media">
                                <img src="{%avatar_url size=128 %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                            {% firstof request.user.get_short_name request.user.get_username %}
                                        <span class="float-right text-sm text-danger"><i class="fas fa-online"></i></span>
                                    </h3>
                                    <p class="text-sm"><small>{% trans 'Member since' %} :</small></p>
                                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i>  <small>{{ request.user.date_joined }}</small></p>
                                </div>
                            </div>
                            <!-- Message End -->
                        </a>
                        <div class="dropdown-divider"></div>
                        <div class="dropdown-footer">
                                <a href="{% block change_password_url %}{% url 'admin:password_change' %}{% endblock %}" class="btn btn-primary btn-sm">{% trans 'Change password' %}</a>
                                <a  href="{% block logout_url %}{% url 'pasundayag:logout' %}{% endblock %}" class="btn btn-danger btn-sm">{%trans 'Sign out'%}</a>
                            </div>
                        
                    </div>
                </li>
            {% endif %}
            {% endblock user_info %}
            {% endblock header_dropdowns %}
        </ul>
    </ul>
        {% endblock nav_custom_menu %}

{% endblock %}
</nav>

templates/adminlte/lib/_main_sidebar.html
{% load adminlte_helpers %}
{% load static %}
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar sidebar-dark-primary elevation-4" style="position:fixed">
     <!-- Brand Logo -->
    {% block logo %}
        <a href="" class="brand-link">
            <img src="{%static 'csu-logo.png' %}" alt="" class="brand-image img-circle elevation-3" style="opacity: .8">
            {% block logo_text %}<span class="brand-text font-weight-light">CSU-PAS </span>{% endblock %}
        </a>
    {% endblock %}
    <!-- sidebar: style can be found in sidebar.less -->
    <div class="sidebar">
        <!-- Sidebar user panel -->
        {% block user_panel %}
        <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% avatar_url size=90 %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{% firstof request.user.name %}</a>
        </div>
      </div>
        {% endblock %}

        {% block form %}{% endblock %}

        <!-- sidebar menu: : style can be found in sidebar.less -->
        {% block nav_links_ul %}
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            {% block nav_links_outer %}
            <li class="nav-header">{% block nav_heading %}MAIN MENU{% endblock %}</li>

            {% block nav_links %}
            {% if request.user.is_superuser %}
                <li class="nav-item">
                    {% url 'pasundayag:dashboard' as url %}
                    <a href="{% url 'pasundayag:dashboard' %}" class="nav-link {% if request.path == url %}active{% endif %}">
                        <i class="nav-icon fas fa-tachometer-alt"></i> 
                        <p>Dashboard</p>
                    </a>
                </li>
                <li class="nav-item has-tree-view ">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-edit"></i> <p>IPCR</p>
                        </p>
                    </a>
                    <ul class="nav nav-treeview menu-open">
                        <li class="nav-item">
                            <a href="{% url 'pasundayag:ipcr-list' %}" class="nav-link">
                                <i class="nav-icon far fa-circle"></i> All IPCRs
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'pasundayag:academic-title-list' %}" class="nav-link">
                                <i class="nav-icon far fa-circle"></i> Academic Title
                            </a>
                        </li>
                    </ul>
                </li>
            {% else %}
                <li class="nav-item">
                    {% url 'pasundayag:dashboard' as url %}
                    <a href="{% url 'pasundayag:personnel-ipcr-list' request.user.id%}" class="nav-link {% if request.path == url %}active{% endif %}">
                        <i class="nav-icon fas fa-edit"></i>
                        <p>My IPCRs</p>
                    </a>
                </li>
            {% endif %}
            {% endblock nav_links %}
            {% endblock nav_links_outer %}
            </ul>
            </nav>
        {% endblock nav_links_ul %}
    </div>
    <!-- /.sidebar -->
</aside>

templates/adminlte/lib/_messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% else %}
        <div class="alert alert-info alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% endif %}
    {% endfor %}
{% endif %}

templates/adminlte/lib/_pagination.html
{% if pager and ROOT_MENU.current_menu.view_name %}
    <ul class="pagination pagination-sm no-margin pull-right">
        <li><a href="{% url ROOT_MENU.current_menu.view_name %}?page=1&{{ pager.url_params }}">&laquo;</a></li>
        {% if pager.page > 2 %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:-2}}&{{ pager.url_params }}">
                    {{ pager.page | add:-2 }}
                </a>
            </li>
        {% endif %}
        {% if pager.page > 1 %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:-1}}&{{ pager.url_params }}">
                    {{ pager.page | add:-1 }}
                </a>
            </li>
        {% endif %}
        <li class="active"><a href="#">{{ pager.page }}</a></li>
        {% if pager.has_next %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:1}}&{{ pager.url_params }}">
                    {{ pager.page | add:1 }}
                </a>
            </li>
        {% endif %}
        {% if pager.has_next_two %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:2}}&{{ pager.url_params }}">
                    {{ pager.page | add:2 }}
                </a>
            </li>
        {% endif %}
        <li>
            <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.last_page}}&{{ pager.url_params }}">
            &raquo;
            </a>
        </li>
    </ul>
{% endif %}

templates/adminlte/lib/_scripts.html
{% load static %}

{% block scripts %}
<script src="{% static 'admin-lte/plugins/jquery/jquery.min.js' %}"></script>
<script src="{% static 'admin-lte/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<script src="{% static 'admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js' %} "></script>


{% block datatable_js %}{% endblock %}

<script src="{% static 'admin-lte/dist/js/adminlte.min.js' %}"></script>
<script src="{% static 'admin-lte/dist/js/demo.js' %}"></script>
{% endblock %}

templates/adminlte/lib/_styles.html
{% load static %}

{% block styles %}
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'admin-lte/plugins/fontawesome-free/css/all.min.css' %}">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'admin-lte/dist/css/adminlte.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
{% endblock %}