account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = "account"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="account/login.html", form_class=UserLoginForm),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(next_page="/account/login/"), name="logout"),
    path("register/", views.account_register, name="register"),
    path("activate/<slug:uidb64>/<slug:token>)/", views.account_activate, name="activate"),
    # Reset password
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/password_reset/password_reset_form.html",
            success_url="password_reset_email_confirm",
            email_template_name="account/password_reset/password_reset_email.html",
            form_class=PwdResetForm,
        ),
        name="pwdreset",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/password_reset/password_reset_confirm.html",
            success_url="password_reset_complete/",
            form_class=PwdResetConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/password_reset_email_confirm/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/Mg/password_reset_complete/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
        name="password_reset_complete",
    ),
    # User dashboard
    path("dashboard/", views.dashboard, name="dashboard"),
    path("profile/edit/", views.edit_details, name="edit_details"),
    path("profile/delete_user/", views.delete_user, name="delete_user"),
    path(
        "profile/delete_confirm/",
        TemplateView.as_view(template_name="account/dashboard/delete_confirm.html"),
        name="delete_confirmation",
    ),
    path("addresses/", views.view_address, name="addresses"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),
    path("user_orders/", views.user_orders, name="user_orders"),
    # Wish List
    path("wishlist", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"),
]

core/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pasundayag.urls", namespace="pasundayag")),
    path("account/", include("account.urls", namespace="account")),
    path("__debug__/", include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/checkout/delivery_address.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Basket Summary{%endblock %}
{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">Delivery Address</h1>
  </div>
  <div class="col-12">
    <p>Please select your delivery address</p>
  </div>
  <hr />
</div>


<div class="container">
  <div class="row g-3">
    {% if addresses|length == 0 %}
    <div class="col-12">There are no delivery addresses, <a href="{% url 'account:add_address' %}">add address</a></div>
    {% else %}
    <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
    
<div class="d-flex bd-highlight ms-0">
  <div class="p-2 flex-grow-1 bd-highlight">Sub Total:</div>
  <div class="p-2 bd-highlight"><span class="fw-bold h5">P</span><span id="sub_total"class="fw-bold h5">{{basket.get_subtotal_price}}</span></div>
</div>
<div class="d-flex bd-highlight">
  <div class="p-2 flex-grow-1 bd-highlight">Delivery Cost:</div>
  <div class="p-2 bd-highlight"><span class="fw-bold h5">P</span><span id="delivery_price" class="fw-bold h5">{{basket.get_delivery_price}}</span></div>
</div>
<div class="d-flex bd-highlight">
  <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
  <div class="p-2 bd-highlight"><span class="fw-bold h5">P</span><span id="total"class="fw-bold h5">{{basket.get_total_price}}</span></div>
</div>
<a role="button" href="{% url 'checkout:payment_selection' %}" class="btn btn-success fw-bold w-100" type="button">Pay Securely</a>
</div>
    
    <div class="col-md-7 col-lg-8">
      {% for address in addresses %}
      {% if not address.default %}
        <h1 class="h5 pt-4">Other Addresses</h1>
      {% endif %}
      <div class="card mb-3 border-1 rounded-0 ipcr-item me-md-4" data-index="{{option.id}}">
        <div class="row g-0">
          <div class="col">
            <div class="card pb-3 rounded-0">
              <div class="card-header bg-white small text-muted">
                {% if address.default %}
                Selected
                {% endif %}
                &nbsp;
              </div>
              <div class="card-body small pb-1">
                <p class="card-text m-0 fw-bold">{{address.full_name}}</p>
                <p class="card-text m-0">{{address.address_line}}</p>
                <p class="card-text m-0">{{address.address_line2}}</p>
                <p class="card-text m-0">{{address.town_city}}</p>
                <p class="card-text m-0">{{address.postcode}}</p>
                <p class="card-text m-0">Phone number: {{address.phone}}</p>
                <div class="pt-5">
                  <a href="{% url 'account:edit_address' address.id %}" class="text-decoration-none">Edit</a>
                  {% if not address.default %}
                  | <a href="{% url 'account:set_default' address.id %}" class="text-decoration-none">Select</a>
                  {% endif %}
                </div>
              </div>
            </div>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}
  </div>

</div>
{% endblock %}

templates/checkout/delivery_choices.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Delivery Options{%endblock %}
{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">Delivery Options</h1>
  </div>
  <div class="col-12">
    <p>Select your delivery options</p>
  </div>
  <hr />
</div>


<div class="container">
{% if messages %}
<div class="alert alert-warning" alert-{{ message.tags }} role="alert">
  {% for message in messages  %}
    {{message|safe}}
  {% endfor %}
</div>
{% endif %}
  <div class="row g-3">
    {% if deliveryoptions|length == 0 %}
    <div class="col-12">There are no delivery options <a href="{% url 'pasundayag:pasundayag_home' %}">Shop</a></div>
    {% else %}
    <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
      <div class="d-flex bd-highlight ms-0">
        <div class="p-2 flex-grow-1 bd-highlight">Sub Total:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">P</span><span id="sub_total"
            class="fw-bold h5">{{basket.get_subtotal_price}}</span></div>
      </div>
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-grow-1 bd-highlight">Delivery Cost:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">P</span><span id="delivery_price"
            class="fw-bold h5">{{basket.get_delivery_price}}</span></div>
      </div>
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">P</span><span id="total"
            class="fw-bold h5">{{basket.get_total_price}}</span></div>
      </div>
      <a role="button" href="{% url "checkout:delivery_address" %}" class="btn btn-success fw-bold w-100"
        type="button">Pay Securely</a>
    </div>
    <div class="col-md-7 col-lg-8">
      {% for option in deliveryoptions %}
      <div class="card mb-3 border-1 rounded-0 ipcr-item me-md-4" data-index="{{option.id}}">
        <div class="row g-0">
          <div class="col-md-2 ps-3 ps-md-4">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-truck mt-2"
              viewBox="0 0 16 16">
              <path
                d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
            </svg>
          </div>
          <div class="col-md-9 ps-md-1">
            <div class="card-body p-1">
              <p class="card-text ps-2 mb-1 pt-1 fw-bold">{{option.delivery_name}}</p>
              <p class="card-text ps-2 pb-3">Your order should be delivered within {{option.delivery_timeframe}}</p>
            </div>
          </div>
          <div class="col-md-1 ps-md-1">
            <input class="align-middle h-100" type="radio" name="deliveryOption" id="{{option.id}}"
              value="{{option.id}}">
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}
  </div>
</div>

<script>
  $('input[type=radio][name=deliveryOption]').on('change', function(e) {
    e.preventDefault();
    $.ajax({
      type: "POST",
      url: '{% url "checkout:basket_update_delivery" %}',
      data: {
        deliveryoption: $(this).val(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {
        document.getElementById("total").innerHTML = json.total;
        document.getElementById("delivery_price").innerHTML = json.delivery_price;
      },
      error: function (xhr, errmsg, err) {},
    });
    
  });
</script>


{% endblock %}

templates/checkout/ipcr_detail_02.html
{% extends "adminlte/base.html" %}
{% load static %}
{% block extra_head %}
<style>
  th {
    text-align: center;
    min-height: 50;
  }
  td {
    text-align: left;
  }
  .form-field {
    width: 100%;
    height: 100%;
    border: none;
    box-sizing: border-box;
    background-color: rgb(244,246,249);
  }
  
</style>
{% endblock extra_head %}

{% block stylesheet %}{% static 'pasundayag/css/pasundayag.css' %}{% endblock %}
{% block title %}
{% if ipcr %}{{ ipcr.title }}{% else %}IPCR{% endif %}
{% endblock %}
{% block content %}
  <div class="container-fluid pb-5">
    <h1 class="h1 font-weight-bold">Individual Performance and Commitment Review</h1>
    {% if pf_ipcr_count > 0 or psf_ipcr_count > 0 %}
      <form method="post">
        {% csrf_token %}
        
        
        <div class="row">
          <div class="col">
            <div class="col col-lg-3 text-start p-3">
              <div class="card border-0">
                <div class="card-body px-0">
                  <p class="card-text px-2 py-3">
                    <a class="h4 text-success text-decoration-none" href="">Ratee: {{ personnel.name }}
                    </a>
                  </p>
                  <div class="p-2">Year: {{year}}</div>
                  <div class="p-2">Period: {{period}}</div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-2">
            <div class="col p-3">
              <div class="text-left">
                <p><b>Rating Scale</b>
                <br>5 - Outstanding
                <br>4 - Very Satisfactory
                <br>3 - Satisfactory
                <br>2 - Unsatisfactory
                <br>1 - Poor</p>
              </div>
            </div>
          </div>
        </div>
        <table data-toggle="table" class="table-bordered">
          <thead>
            <tr>
              <th scope="col" rowspan="2">MFO/PAP</th>
              <th scope="col" rowspan="2">SUCCESS INDICATORS (Targets + Measures) </th>
              <th scope="col" rowspan="2">Actual Accomplishments</th>
              <th scope="col" colspan="4">Rating</th>
              <th scope="col" rowspan="2">Remarks</th>

            </tr>
            <tr>
              <th scope="col" width="3%">Q</th>
              <th scope="col" width="3%">E</th>
              <th scope="col" width="3%">T</th>
              <th scope="col" width="3%">A</th>
            </tr>
            <tr>
          </thead>
          <tbody>
          <!-- Loop area_list -->
          {% for area in area_list %}
            <tr class="font-weight-bold">
              <td>{{area.description}} ({{area.percent|floatformat:0}}%)</td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
            </tr>

            <!-- Loop function_list -->
            {% for function in function_list %}
              {% if function.area == area %}
                  <tr>
                    <td {% if function.area.description == '2 CORE FUNCTIONS' %}class="font-weight-bold" {% endif%}>{% if function.mfo_pap %}{{function.mfo_pap}}{% endif %}</td>
                    <td>{% if function.indicators %}{{function.indicators}}{% endif %}</td>
                    {% for pf_ipcr in pf_ipcr_list %}
                        {% if pf_ipcr.function == function %}
                        <td>
                          {% if pf_ipcr.function_id == function.id %}
                            {{pf_ipcr.accomplishments }}
                          {% endif %}
                        </td>
                        <td>
                          {% if pf_ipcr.function == function %}
                            {% if pf_ipcr.rating_Q > 0 %}{{pf_ipcr.rating_Q }}{% else %}{% endif %}
                          {% endif %}
                        </td>
                        <td>
                          {% if pf_ipcr.function == function %}
                            {% if pf_ipcr.rating_E > 0 %}{{pf_ipcr.rating_E }}{% else %}{% endif %}
                          {% endif %}
                        </td>
                        <td>
                          {% if pf_ipcr.function == function %}
                            {% if pf_ipcr.rating_T > 0 %}{{pf_ipcr.rating_T }}{% else %}{% endif %}
                          {% endif %}
                        </td>
                        <td>
                          
                        </td>
                        <td>
                          {% if pf_ipcr.function == function %}
                            {{pf_ipcr.remarks }}
                          {% endif %}
                        </td>
                        {% endif %}
                      {% endfor %}
                    
                  </tr>
                  </tr>
                <!-- Loop subfunction_list -->
                {% for subfunction in sfunction_list %}
                  {% if subfunction.function == function %}
                    <tr>
                      <td>{% if subfunction.mfo_pap %}{{subfunction.mfo_pap}}{% endif %}</td>
                      <td>{% if subfunction.indicators %}{{subfunction.indicators}}{% endif %}</td>
                      {% for psf_ipcr in psf_ipcr %}
                        {% if psf_ipcr.subfunction == subfunction %}
                      
                        <td>
                          {% if psf_ipcr.subfunction_id == function.id %}
                            {{psf_ipcr.accomplishments }}
                          {% endif %}
                        </td>
                        <td>
                          {% if psf_ipcr.subfunction == subfunction %}
                            {% if psf_ipcr.rating_Q > 0 %}{{psf_ipcr.rating_Q }}{% else %}{% endif %}
                          {% endif %}
                        </td>
                        <td>
                          {% if psf_ipcr.subfunction == subfunction %}
                            {% if psf_ipcr.rating_E > 0 %}{{psf_ipcr.rating_E }}{% else %}{% endif %}
                          {% endif %}
                        </td>
                        <td>
                          {% if psf_ipcr.subfunction == subfunction %}
                            {% if psf_ipcr.rating_T > 0 %}{{psf_ipcr.rating_T }}{% else %}{% endif %}
                          {% endif %}
                        </td>
                        <td>
                          
                        </td>
                        <td>
                          {% if psf_ipcr.subfunction == subfunction %}
                            {{psf_ipcr.remarks }}
                          {% endif %}
                        </td>
                        {% endif %}
                      {% endfor %}
                    </tr>
                    {% if subfunction.mfo_pap == "2.1.4 PES Students' Rating"%}
                      <tr>
                        <td></td>
                        <td>[22, 23) :  4</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td> 
                      </tr>
                      <tr>
                        <td></td>
                        <td>[20, 22) :  3</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td> 
                      </tr>
                      <tr>
                        <td></td>
                        <td>[19, 20) :  2</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td> 
                      </tr>
                      <tr>
                        <td></td>
                        <td>Below 19  :  1  </td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td> 
                      </tr>
                    {% endif %}
                  {% endif %}
                  
                {% endfor %}
                {% if function.area.description == "2 CORE FUNCTIONS" %}
                <tr>
                  <td height="50"></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td class="bg-secondary"></td>
                  <td></td>
                </tr>
                {% endif %}
              {% endif %}
            {% endfor %}
            {% if not  area.description == "2 CORE FUNCTIONS" %}
                <tr>
                  <td height="50"></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td class="bg-secondary"></td>
                  <td></td>
                </tr>
              {% endif %}
          {% endfor %}
          </tbody>
        </table>
        <div class=py-2>
          <button class="btn btn-primary" type="submit">Submit</button>
        </div>
      </form>
    {% else %}
    <div class="col-12">There are currently no active IPCR for <strong>{{period}}</strong> of the year <strong>{{year}}</strong> for <strong>{{personnel.name}}</strong>.
    </div> 
    {% endif %}
    <script src="https://unpkg.com/bootstrap-table@1.21.2/dist/bootstrap-table.min.js"></script>

    <script>
      $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
          type: 'POST',
          url: '{% url "basket:basket_add" %}',
          data: {
            ipcrid: $('#add-button').val(),
            ipcrqty: $('#select option:selected').text(),
            csrfmiddlewaretoken: "{{csrf_token}}",
            action: 'post'
          },
          success: function (json) {
            document.getElementById("basket-qty").innerHTML = json.qty
          },
          error: function (xhr, errmsg, err) { }
        });
      })
    </script>
{% endblock %}

templates/checkout/payment_selection.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Payment Selection{%endblock %}
{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">Delivery Options</h1>
  </div>
  <div class="col-12">
    <p>Please select your delivery option</p>
  </div>
  <hr />
</div>

<div class="container">
  <div class="row g-3">
    <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
      <div class="d-flex bd-highlight ms-0">
        <div class="p-2 flex-grow-1 bd-highlight">Sub Total:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">P</span><span id="sub_total"
            class="fw-bold h5">{{basket.get_subtotal_price}}</span></div>
      </div>
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-grow-1 bd-highlight">Delivery Cost:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">P</span><span id="delivery_price"
            class="fw-bold h5">{{basket.get_delivery_price}}</span></div>
      </div>
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">P</span><span id="total"
            class="fw-bold h5">{{basket.get_total_price}}</span></div>
      </div>
    </div>
    <div class="col-md-7 col-lg-8 pe-0 pe-md-5">
      <div id="paypal-button-container"></div>
    </div>
  </div>
</div>
<script
  src="https://www.paypal.com/sdk/js?client-id=AZQiAqo_G8vygoAIT9tAL-Z6MQd49xERaY6a3N0ijCRXkubEyMnylsk1qjxNIFM2iAFomcSTfq4yW47O&currency=GBP"
  data-sdk-integration-source="button-factory">
</script>
    <script>
  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
      var cookies = document.cookie.split(';');
      for (var i = 0; i < cookies.length; i++) {
        var cookie = cookies[i].trim();
        if (cookie.substring(0, name.length + 1) === (name + '=')) {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }
  var csrftoken = getCookie('csrftoken');



  function initPayPalButton() {
    paypal.Buttons({
      style: {
        shape: 'rect',
        color: 'gold',
        layout: 'vertical',
        label: 'paypal',

      },
    createOrder: function (data, actions) {
        return actions.order.create({
          purchase_units: [{
            "amount": {
              "currency_code": "GBP",
              "value": '{{basket.get_total_price}}'
            }
          }]
        });
      },
    onApprove: function (data) {
        var url = "{% url 'checkout:payment_complete' %}"
        return fetch(url, {
          method: 'POST',
          headers: {
            'content-type': 'application/json',
            'X-CSRFToken': csrftoken,
          },
          body: JSON.stringify({
            orderID: data.orderID
          })
        }).then(function () {
          location.href = '{% url 'checkout:payment_successful' %}';
        })
      },
    }).render('#paypal-button-container');
  }
  initPayPalButton();

    </script>

{% endblock %}

templates/checkout/payment_successful.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Payment Successful{%endblock %}
{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">Payment Successful</h1>
  </div>
  <div class="col-12">
    <p>Order Summary</p>
  </div>
  <hr />
  <div class="col-12">
    <p>View all <a href="{% url 'account:user_orders'%}">orders</a></p>
  </div>
</div>


{% endblock %}

templates/checkout/rate_personnel_02.html
{% extends "adminlte/base.html" %}
{% load static %}
{% block extra_head %}
<style>
  th {
    text-align: center;
    min-height: 50;
  }
  td {
    text-align: left;
  }
  .form-field {
    width: 100%;
    height: 100%;
    border: none;
    box-sizing: border-box;
    background-color: rgb(244,246,249);
  }
  
</style>
{% endblock extra_head %}

{% block stylesheet %}{% static 'pasundayag/css/pasundayag.css' %}{% endblock %}
{% block title %}
{% if ipcr %}{{ ipcr.title }}{% else %}IPCR{% endif %}
{% endblock %}
{% block content %}
  <div class="container-fluid pb-5">
    <h1 class="h1 font-weight-bold">Individual Performance and Commitment Review</h1>
    <form method="post">
      {% csrf_token %}
      
      
      <div class="row">
        <div class="col">
          <div class="col col-lg-3 text-start p-3">
            <div class="card border-0">
              <div class="card-body px-0">
                <p class="card-text px-2 py-3">
                  <a class="h4 text-success text-decoration-none" href="">Ratee: {{ personnel.name }}
                  </a>
                </p>
                <div class="p-2">Year: {{year}}</div>
                <div class="p-2">Period: {{period}}</div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-2">
          <div class="col p-3">
            <div class="text-left">
              <p><b>Rating Scale</b>
              <br>5 - Outstanding
              <br>4 - Very Satisfactory
              <br>3 - Satisfactory
              <br>2 - Unsatisfactory
              <br>1 - Poor</p>
            </div>
          </div>
        </div>
      </div>
      <table data-toggle="table" class="table-bordered">
        <thead>
          <tr>
            <th scope="col" rowspan="2">MFO/PAP</th>
            <th scope="col" rowspan="2">SUCCESS INDICATORS (Targets + Measures) </th>
            <th scope="col" rowspan="2">Actual Accomplishments</th>
            <th scope="col" colspan="3">Rating</th>
            <th scope="col" rowspan="2">Remarks</th>

          </tr>
          <tr>
            <th scope="col" width="3%">Q</th>
            <th scope="col" width="3%">E</th>
            <th scope="col" width="3%">T</th>
          </tr>
          <tr>
        </thead>
        <tbody>
        <!-- Loop area_list -->
        {% for area in area_list %}
          <tr class="font-weight-bold">
            <td>{{area.description}} ({{area.percent|floatformat:0}}%)</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          
          
          {% for function in function_list %}
            {% if function.area == area %}
            <tr class="{%if area.description == "2 CORE FUNCTIONS" %}font-weight-bold {% endif %}">
              <td>{{function.mfo_pap}}</td>
              <td>{{function.indicators}}</td>
              <td>{{form1.accomplishments}}</td>
              <td>{{form1.rating_Q}}</td>
              <td>{{form1.rating_E}}</td>
              <td>{{form1.rating_T}}</td>
              <td>{{form1.remarks}}</td>
            </tr>
            {% for subfunction in sfunction_list %}
              {% if subfunction.function == function %}
                <tr>
                  <td>{{subfunction.mfo_pap}}</td>
                  <td>{{subfunction.indicators}}</td>
                  <input type="hidden" value="{{personnel.id}}">
                  <input type="hidden" value="{{year}}">
                  <input type="hidden" value="{{period}}">
                  <td>{{form2.accomplishments}}</td>
                  <td>{{form2.rating_Q}}</td>
                  <td>{{form2.rating_E}}</td>
                  <td>{{form2.rating_T}}</td>
                  <td>{{form2.remarks}}</td>
                </tr>
              {% endif %}
            {% endfor %}
            {% endif %}
          {% endfor %}

        {% endfor %}
        </tbody>
      </table>
        {% if area_list.has_other_pages %}
            <nav class="m-2" aria-label="Page navigation container wow fadeInUp"></nav>
            <ul class="pagination justify-content-center wow fadeInUp">
                {% if area_list.has_previous %}
                <li><a href="?page={{ area_list.previous_page_number }}"
                        class="btn btn-primary page-link wow fadeInUp">&laquo; Prev </a></li>
                {% endif %}
                {% if area_list.has_next %}
                <li><a href="?page={{ area_list.next_page_number }}" class="btn btn-primary page-link wow fadeInUp">
                        Next &raquo;</a></li>
                {% endif %}
            </ul>
            </nav>
          {% endif %}
      <div class=py-2>
        <button class="btn btn-primary" type="submit">Submit</button>
      </div>
    </form>
    <script src="https://unpkg.com/bootstrap-table@1.21.2/dist/bootstrap-table.min.js"></script>

    <script>
      $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
          type: 'POST',
          url: '{% url "basket:basket_add" %}',
          data: {
            ipcrid: $('#add-button').val(),
            ipcrqty: $('#select option:selected').text(),
            csrfmiddlewaretoken: "{{csrf_token}}",
            action: 'post'
          },
          success: function (json) {
            document.getElementById("basket-qty").innerHTML = json.qty
          },
          error: function (xhr, errmsg, err) { }
        });
      })
    </script>
{% endblock %}